package temperatureconverter;

import java.text.DecimalFormat;

/**
 * GUI window class
 * @author kritterbusch
 */
public class TempConverterWindow extends javax.swing.JFrame {

    double num;
    double ansCelsius;
    double ansFahrenheit;
    String msg;
    private final TemperatureConverterService tempConverter;
    
    /**
     * Creates new form TempConverterWindow
     */
    public TempConverterWindow() {
        initComponents();
        tempConverter = new TemperatureConverterService();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpSelection = new javax.swing.ButtonGroup();
        txtEnterValue = new javax.swing.JTextField();
        btnConvert = new javax.swing.JButton();
        txtConverterTitle = new javax.swing.JLabel();
        txtInstruction = new javax.swing.JLabel();
        ConversionSelection = new javax.swing.JPanel();
        slctCtoF = new javax.swing.JRadioButton();
        slctFtoC = new javax.swing.JRadioButton();
        TempOutput = new javax.swing.JPanel();
        lblOutputMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtEnterValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterValueActionPerformed(evt);
            }
        });

        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        txtConverterTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtConverterTitle.setForeground(new java.awt.Color(204, 0, 51));
        txtConverterTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtConverterTitle.setText("Temperature Converter");

        txtInstruction.setText("Enter Value to Convert");

        ConversionSelection.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Conversion Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        ConversionSelection.setToolTipText("");

        btnGrpSelection.add(slctCtoF);
        slctCtoF.setSelected(true);
        slctCtoF.setText("Celsius to Fahrenheit");
        slctCtoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slctCtoFActionPerformed(evt);
            }
        });

        btnGrpSelection.add(slctFtoC);
        slctFtoC.setText("Fahrenheit to Celsius");
        slctFtoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slctFtoCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConversionSelectionLayout = new javax.swing.GroupLayout(ConversionSelection);
        ConversionSelection.setLayout(ConversionSelectionLayout);
        ConversionSelectionLayout.setHorizontalGroup(
            ConversionSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConversionSelectionLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(ConversionSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(slctFtoC)
                    .addComponent(slctCtoF))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        ConversionSelectionLayout.setVerticalGroup(
            ConversionSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConversionSelectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slctCtoF)
                .addGap(18, 18, 18)
                .addComponent(slctFtoC)
                .addGap(20, 20, 20))
        );

        TempOutput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Temperature Output", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N

        lblOutputMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout TempOutputLayout = new javax.swing.GroupLayout(TempOutput);
        TempOutput.setLayout(TempOutputLayout);
        TempOutputLayout.setHorizontalGroup(
            TempOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TempOutputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOutputMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );
        TempOutputLayout.setVerticalGroup(
            TempOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TempOutputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOutputMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtConverterTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TempOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConversionSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnConvert)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(txtInstruction)
                .addGap(18, 18, 18)
                .addComponent(txtEnterValue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtConverterTitle)
                .addGap(18, 18, 18)
                .addComponent(ConversionSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInstruction)
                    .addComponent(txtEnterValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TempOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConvert)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnterValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterValueActionPerformed
        String number = txtEnterValue.getText();
        double num = Double.valueOf(number);
    }//GEN-LAST:event_txtEnterValueActionPerformed

    private void slctCtoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slctCtoFActionPerformed
        slctCtoF.isSelected();
    }//GEN-LAST:event_slctCtoFActionPerformed

    private void slctFtoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slctFtoCActionPerformed
        slctFtoC.isSelected();
    }//GEN-LAST:event_slctFtoCActionPerformed

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        DecimalFormat formatter = new DecimalFormat("#0.0");
        num = Double.valueOf(txtEnterValue.getText());

        if (slctFtoC.isSelected()) {
            ansCelsius = ((num - 32) * (.555555556));
            msg = num + " degrees Fahrenheit is " + formatter.format(ansCelsius) + " degrees Celsius.";
            lblOutputMessage.setText(msg);
            
        } else if (slctCtoF.isSelected()){
            ansFahrenheit = (num * 1.8) + 32;
            msg = num + " degrees Celsius is " + formatter.format(ansFahrenheit) + " degrees Fahrenheit.";
            lblOutputMessage.setText(msg);
    }//GEN-LAST:event_btnConvertActionPerformed
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConversionSelection;
    private javax.swing.JPanel TempOutput;
    private javax.swing.JButton btnConvert;
    private javax.swing.ButtonGroup btnGrpSelection;
    private javax.swing.JLabel lblOutputMessage;
    private javax.swing.JRadioButton slctCtoF;
    private javax.swing.JRadioButton slctFtoC;
    private javax.swing.JLabel txtConverterTitle;
    private javax.swing.JTextField txtEnterValue;
    private javax.swing.JLabel txtInstruction;
    // End of variables declaration//GEN-END:variables
}
